const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const optionsV1 = {
  swaggerDefinition : {
    info: {
      title: 'Getir Assigment',
      version: '1.0',
      description: 'General REST APIs with autogenerated swagger doc',
    },
    basePath: "/api",
    securityDefinitions: {
      auth: {
        type: 'apiKey',
        name: 'Authorization'
      }
    },
    security: [
      { auth: [] }
    ]
  },
  // List of files to be processes. 
  apis: ['./docs/*.yaml'],
  
};

const swaggerSpecV1 = swaggerJsdoc(optionsV1);
const swaggerHtmlV1 = swaggerUi.generateHTML(swaggerSpecV1, optionsV1)

module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serveFiles(swaggerSpecV1, optionsV1))
    app.get('/api-docs', (req, res) => { res.send(swaggerHtmlV1) });
}
